refactor(git): prepare commit message hook
- check for version of sed
- cleanup commit message files

diff --git a/config/git/hooks/prepare-commit-msg b/config/git/hooks/prepare-commit-msg
--- a/config/git/hooks/prepare-commit-msg
+++ b/config/git/hooks/prepare-commit-msg
@@ -5,6 +5,16 @@ COMMIT_MSG_FILE=$1
 COMMIT_SOURCE=$2
 # SHA1=$3
 
+# Check for GNU sed (required for 0,/pattern/ syntax)
+if command -v gsed &>/dev/null; then
+  SED="gsed"
+elif sed --version 2>&1 | grep -q "GNU sed"; then
+  SED="sed"
+else
+  echo "Error: GNU sed is required but not found. Install with: brew install gnu-sed"
+  exit 1
+fi
+
 # exit if commit is a fixup
 grep -q 'fixup' "$COMMIT_MSG_FILE" && exit 0
 
@@ -12,64 +22,66 @@ grep -q 'fixup' "$COMMIT_MSG_FILE" && exit 0
 branch_name=$(git rev-parse --abbrev-ref HEAD)
 
 # check that branch has jira id and title; i.e. "feature/ABC-123-description"
-jira_tag_id=$(echo "$branch_name" | sed -nr 's,[a-z]*/?([A-Z0-9]+-[0-9]+)-.+,\1,p')
+jira_tag_id=$(echo "$branch_name" | $SED -nr 's,[a-z]*/?([A-Z0-9]+-[0-9]+)-.+,\1,p')
 
 if [[ -n "$jira_tag_id" ]]; then
-	# exit if jira_tag_id is found already in the commit message
-	grep -q "^$jira_tag_id:" "$COMMIT_MSG_FILE" && exit 0
+  # exit if jira_tag_id is found already in the commit message
+  grep -q "^$jira_tag_id:" "$COMMIT_MSG_FILE" && exit 0
 
-	printf "\n󰌃 Prepending Jira issue id to commit message...\n\n"
+  printf "\n󰌃 Prepending Jira issue id to commit message...\n\n"
 
-	# check  if commit was initiated with editor/template
-	if [[ "$COMMIT_SOURCE" == "template" ]]; then
-		command="0,/^$/{s/^$/$jira_tag_id: /}"
-	else
-		# ...or with -m flag
-		command="1s/^/$jira_tag_id: /"
-	fi
+  # check  if commit was initiated with editor/template
+  if [[ "$COMMIT_SOURCE" == "template" ]]; then
+    command="0,/^$/{s/^$/$jira_tag_id: /}"
+  else
+    # ...or with -m flag
+    command="1s/^/$jira_tag_id: /"
+  fi
 
-	# if command is set, prepend jira issue id to the commit message
-	[[ -n $command ]] && sed -i.bak -e "$command" "$COMMIT_MSG_FILE"
+  # prepend jira issue id to the commit message
+  $SED -i.bak -e "$command" "$COMMIT_MSG_FILE"
+  rm -f "$COMMIT_MSG_FILE.bak"
 fi
 
 conventional_commit_types=(
-	"build"
-	"chore"
-	"ci"
-	"docs"
-	"feat"
-	"fix"
-	"perf"
-	"refactor"
-	"revert"
-	"style"
-	"test"
+  "build"
+  "chore"
+  "ci"
+  "docs"
+  "feat"
+  "fix"
+  "perf"
+  "refactor"
+  "revert"
+  "style"
+  "test"
 )
 
 # check if branch has conventional commit type before /
-branch_slug=$(echo "$branch_name" | sed -nr 's,([a-z]+)/?.+,\1,p')
+branch_slug=$(echo "$branch_name" | $SED -nr 's,([a-z]+)/?.+,\1,p')
 
 # check if branch_slug is in conventional_commit_types array
 if [[ " ${conventional_commit_types[*]} " == *" $branch_slug "* ]]; then
-	conventional_commit_type=$branch_slug
+  conventional_commit_type=$branch_slug
 fi
 
 if [[ -n "$conventional_commit_type" ]]; then
-	# exit if conventional_commit_type is found already in the commit message
-	for type in "${conventional_commit_types[@]}"; do
-		grep -q "^$type\((\w\+)\)\?:" "$COMMIT_MSG_FILE" && exit 0
-	done
+  # exit if conventional_commit_type is found already in the commit message
+  for type in "${conventional_commit_types[@]}"; do
+    grep -q "^$type\(([[:alnum:]_]\+)\)\?:" "$COMMIT_MSG_FILE" && exit 0
+  done
 
-	printf "\n Prepending conventional commit type to commit message...\n\n"
+  printf "\n Prepending conventional commit type to commit message...\n\n"
 
-	# check if commit was initiated with editor/template
-	if [[ "$COMMIT_SOURCE" == "template" ]]; then
-		command="0,/^$/{s/^$/$conventional_commit_type: /}"
-	else
-		# ...or with -m flag
-		command="1s/^/$conventional_commit_type: /"
-	fi
+  # check if commit was initiated with editor/template
+  if [[ "$COMMIT_SOURCE" == "template" ]]; then
+    command="0,/^$/{s/^$/$conventional_commit_type: /}"
+  else
+    # ...or with -m flag
+    command="1s/^/$conventional_commit_type: /"
+  fi
 
-	# if command is set, prepend conventional commit type to the commit message
-	[[ -n $command ]] && sed -i.bak -e "$command" "$COMMIT_MSG_FILE"
+  # prepend conventional commit type to the commit message
+  $SED -i.bak -e "$command" "$COMMIT_MSG_FILE"
+  rm -f "$COMMIT_MSG_FILE.bak"
 fi
